---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
              name: http
              protocol: TCP
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kibana
spec:
  selector:
    matchLabels:
      run: kibana
  template:
    metadata:
      labels:
        run: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:6.6.2
          env:
            - name: ELASTICSEARCH_URL
              value: "http://elasticsearch:9200"
            - name: XPACK_SECURITY_ENABLED
              value: "true"
            - name: SERVER_BASEPATH
              value: "/kibana"
          ports:
            - containerPort: 5601
              name: http
              protocol: TCP
